"""create cash_sessions and link sales to sessions

Revision ID: 53a116a0edeb
Revises: 0d5c387d25fb
Create Date: 2026-09-29 15:28:29.123571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a116a0edeb'
down_revision: Union[str, Sequence[str], None] = '0d5c387d25fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='session_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_user_id'), 'cash_sessions', ['user_id'], unique=False)
    op.add_column('sales', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_session_id'), 'sales', ['session_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'cash_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_session_id'), table_name='sales')
    op.drop_column('sales', 'session_id')
    op.drop_index(op.f('ix_cash_sessions_user_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    # ### end Alembic commands ###
