"""add shop name uniqueness constraint

Revision ID: 56a6c1da27ff
Revises: 988b8d47d044
Create Date: 2026-10-04 22:12:51.892033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a6c1da27ff'
down_revision: Union[str, Sequence[str], None] = '988b8d47d044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shops_name', 'shops', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shops_name', 'shops', type_='unique')
    # ### end Alembic commands ###
